/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Llamma__factory } from "./Llamma__factory";
export { Multicaller__factory } from "./Multicaller__factory";
