semi: false
printWidth: 120
singleQuote: true
trailingComma: all
arrowParens: avoid
tabWidth: 4
bracketSpacing: true
overrides:
  - files:
      - "*.yaml"
      - "*.yml"
      - "*.json"
    options:
      tabWidth: 2
