/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Llamma } from "./Llamma";
export type { Multicaller } from "./Multicaller";
export * as factories from "./factories";
export { Llamma__factory } from "./factories/Llamma__factory";
export { Multicaller__factory } from "./factories/Multicaller__factory";
